version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: erm_app
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
      - ./laravel/vendor:/var/www/laravel/vendor
      - ./laravel/storage:/var/www/laravel/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - redis
      - mongo
    networks:
      - erm_net

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: erm_soketi
    environment:
      - DEFAULT_APP_ID=app-id
      - DEFAULT_APP_KEY=app-key
      - DEFAULT_APP_SECRET=app-secret
      - PORT=6001
      - METRICS_PORT=9601
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - erm_net

  php-worker:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: erm_php_worker
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    command: ["sh","-c","php artisan migrate --force || true; php artisan queue:work --sleep=3 --tries=3"]
    depends_on:
      redis:
        condition: service_started
      mongo:
        condition: service_healthy
      app:
        condition: service_started
    networks:
      - erm_net

  subscriber:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: erm_subscriber
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    command: ["sh","-c","php artisan mcu:subscribe"]
    depends_on:
      - redis
      - app
    networks:
      - erm_net

  nginx:
    image: nginx:1.29-alpine
    container_name: erm_nginx
    ports:
      - "80:80"
    volumes:
      - ./laravel:/var/www/laravel:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - php-worker
    networks:
      - erm_net

  redis:
    image: redis:8.2-alpine
    container_name: erm_redis
    ports:
      - "6379:6379"
    networks:
      - erm_net

  mongo:
    image: mongo:8.2
    container_name: erm_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/create-app-user.js:/docker-entrypoint-initdb.d/create-app-user.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootsecret123
      MONGO_INITDB_DATABASE: mcu_db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - erm_net
  node-bridge:
    build:
      context: ./node-bridge
      dockerfile: Dockerfile
    container_name: erm_node_bridge
    working_dir: /usr/src/app
    volumes:
      - ./node-bridge:/usr/src/app
    command: ["node","dist/index.js"]
    ports:
      - "9000:9000"
    depends_on:
      - redis
    networks:
      - erm_net

volumes:
  mongo-data:

networks:
  erm_net:
    driver: bridge
